name: Deploy Nodejs code on EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # got access to your code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            echo "Deploying code to EC2"
            cd /home/ubuntu/deploy-test
            git pull origin main
            pm2 restart 0

        